In [26]:
from __future__ import division
from __future__ import print_function
import requests
import json
import urllib
import urllib.request

In [27]:
# importação de dados

import pandas as pd
df = pd.read_csv("visitas.csv", sep=';',decimal=",",dtype=float) # importante informacao separado por ponto e virgula e trocar potno é no decimal
df.head()

,ID Visitante,ID Loja,Latitude,Longitude,Mes,Ano,Total de visitas,Total semanas com visitas,Media do numero de visitas por semana,Prioridade,Tempo em loja,Jornada de trabalho diaria
0,5144.0,772.0,-3.755253,-38.488490,1.0,2019.0,8.0,4.0,2.00,2.0,28800.0,28800.0
1,5144.0,842.0,-3.771741,-38.482682,1.0,2019.0,2.0,1.0,2.00,2.0,28800.0,28800.0
2,5144.0,983.0,-3.755391,-38.539536,1.0,2019.0,8.0,3.0,2.67,4.0,28800.0,28800.0
3,5144.0,4007.0,-3.792897,-38.479906,1.0,2019.0,1.0,1.0,1.00,3.0,14400.0,28800.0
4,5127.0,1704.0,-16.093596,-47.982968,1.0,2019.0,27.0,5.0,5.40,1.0,28800.0,28800.0

In [29]:
# separação dos dados de interesse
df2=df[['Longitude','Latitude'] ][0:12] #separa os 10 primeiros das colunas Longitude e Latitude

df2.head()

   Longitude   Latitude
0 -38.488490  -3.755253
1 -38.482682  -3.771741
2 -38.539536  -3.755391
3 -38.479906  -3.792897
4 -47.982968 -16.093596

In [30]:
# make sure you can connect to Google's server
import requests
try:
  response = requests.get('http://www.google.com')
except:
  print ('Can\'t connect to Google\'s server')
  raw_input('Press any key to exit.')
  quit()

In [31]:
data=df2 #fazendo uma seleção de dados

In [33]:
import pandas as pd

def create_distance_matrix(data):
  addresses = data[['Longitude','Latitude'] ]
  #addresses = data['Longitude' ]
  API_key = 'AIzaSyB3pWwZR8EuBxMJ5_lvJH3hLcnaOS-kGKE'
  # Distance Matrix API only accepts 100 elements per request, so get rows in multiple requests.
  max_elements = 100
  num_addresses = len(addresses) # 16 in this example.
  # Maximum number of rows that can be computed per request (6 in this example).
  max_rows = max_elements // num_addresses
  # num_addresses = q * max_rows + r (q = 2 and r = 4 in this example).
  q, r = divmod(num_addresses, max_rows)
  dest_addresses = addresses #####
  distance_matrix = []
  # Send q requests, returning max_rows rows per request.
  for i in range(q):
    origin_addresses = addresses[i * max_rows: (i + 1) * max_rows]
    origin_addresses = pd.DataFrame(origin_addresses) # é preciso mudar para o formato para não dar problema
    origin_addresses.index = range(len(origin_addresses))# mudança da porra de indice que por algum motivo do inferno começa de outro numero
    response = send_request(origin_addresses, dest_addresses, API_key)
    distance_matrix += build_distance_matrix(response)

  # Get the remaining remaining r rows, if necessary.
  if r > 0:
    origin_addresses = addresses[q * max_rows: q * max_rows + r]
    origin_addresses = pd.DataFrame(origin_addresses) # é preciso mudar para o formato para não dar problema
    origin_addresses.index = range(len(origin_addresses))# mudança da porra de indice que por algum motivo do inferno começa de outro numero
    response = send_request(origin_addresses, dest_addresses, API_key) ######aqui envia para a próxima caixa definida
    distance_matrix += build_distance_matrix(response)
  return distance_matrix

In [34]:
def send_request(origin_addresses, dest_addresses, API_key):
  """ Build and send request for the given origin and destination addresses."""
  def build_address_str(addresses):
    # Build a pipe-separated string of addresses
    address_str = ''
    for i in range(len(addresses) - 1):
        address_str += str(addresses['Latitude'][i]) + ',' + str(addresses['Longitude'][i])+ '|'
    
    address_str += str(addresses['Latitude'][len(addresses) - 1]) + ',' + str(addresses['Longitude'][len(addresses) - 1])
    return address_str

  request = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial'
  origin_address_str = build_address_str(origin_addresses)
  dest_address_str = build_address_str(dest_addresses)
  request = request + '&origins=' + origin_address_str + '&destinations=' + \
                       dest_address_str + '&key=' + API_key

  
  with urllib.request.urlopen(request) as url:
    jsonResult = url.read()
  response = json.loads(jsonResult)

  #jsonResult = urllib.urlopen(request).read()
  #response = json.loads(jsonResult)
  return response

In [35]:
def build_distance_matrix(response):
  distance_matrix = []
  for row in response['rows']:
    row_list = [row['elements'][j]['distance']['value'] for j in range(len(row['elements']))]
    distance_matrix.append(row_list)
  return distance_matrix

In [36]:
def main():
  """Entry point of the program"""
  # Create the data.
  data = df2
  addresses = data[['Longitude','Latitude'] ]
  API_key = 'AIzaSyB3pWwZR8EuBxMJ5_lvJH3hLcnaOS-kGKE'
  distance_matrix = create_distance_matrix(data)

  print(distance_matrix)
if __name__ == '__main__':
  main()

[]